### ISSUE TITLE
Do not show Foreword Sharecards on english

### ISSUE THREAD

**Issue by MRigal** [technologiestiftung/citylab-jahresbericht-2022#20]
Hi @ZenVega !

Eine letzte Sache vielleicht morgen, die @PiaGralki  mir mitgegeben hat:

Die ShareCards hier sind nicht erwünscht auf Englisch, könntest du diese auf Englisch verstecken?

https://github.com/technologiestiftung/citylab-jahresbericht-2022/blob/44d58468004f81f8c7c9972111caf96f95cefe6a/src/sections/Foreword/index.jsx#L14-L22

Pia, was mir hier auch auffällt, ist dass es kein "alt" Text zu den Bildern. Vielleicht kannst du es hier noch hinfügen?

**Comment by MRigal** [comment]
@PiaGralki neben diesen 4 Werte, könntest du auch kurz hier noch ein Text hinzufügen, vermutlich "CityLAB Logo": https://github.com/technologiestiftung/citylab-jahresbericht-2022/blob/2e386a2b1c00c7b12f1010e391f2224c34b227f0/src/components/Intro/index.js#L8
Das sind die letzten Teile wo kein Text für die Bilder zur Verfügung stehen

**Comment by ZenVega** [comment]
Done!
